conf:
  timeout: 30
  
exec_list:
# 認証方式で変更
# パスワード認証用
# - expect: '.*assword'
#   exec: '{{ __loginpassword__ }}'
# 鍵認証用
  - expect: '@'
    exec: echo ssh-open


# ファイル管理・テンプレート管理
# 作業対象への転送は難しそうなので、一旦存在が確認できて中身が空っぽでなければよろし
  - localaction: ls -al {{ CPF_01 }}
  - localaction: ls -al {{ TPF_01 }}

  - localaction: '[ $(wc -m < {{ CPF_01 }}) -ne 0 ] && exit 0 || exit 1'
  - localaction: '[ $(wc -m < {{ TPF_01 }}) -ne 0 ] && exit 0 || exit 1'


# 代入値確認

  - command: "echo -n {{ VAR_1 }},{{ VAR_2 }}"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30

  - command: "echo -n {{ item.0 }}:{{ item.1 }}"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30
    with_items:
      - '{{ VAR_array_1 }}'
      - '{{ VAR_array_2 }}'

  - command: "echo -n {{ VAR_key_1 }},{{ VAR_key_2 }}"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30

  - command: "echo -n {{ item.0 }}:{{ item.1 }}"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30
    with_items:
      - '{{ VAR_key_array_1 }}'
      - '{{ VAR_key_array_2 }}'


# Pioneerで使用できるモジュールを一度は実施

  - localaction: mkdir -p 0755 {{ __workflowdir__ }}/{{ __inventory_hostname__ }}

  - state: cat /etc/hosts
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    parameter:
      - '127.0.0.1'
      - 'localhost'

  - command: "echo -n {{ VAR_1 }} {{ VAR_2 }} > /tmp/testfile"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30

  - state: cat /tmp/testfile
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    stdout_file: '{{ __workflowdir__ }}/{{ __inventory_hostname__ }}/vartest1'
    parameter:
      - '{{ VAR_1 }}'
      - '{{ VAR_2 }}'

  - state: cat /tmp/testfile
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    stdout_file: '{{ __workflowdir__ }}/{{ __inventory_hostname__ }}/vartest2'
    ignore_errors: yes

  - command: "rm -f /tmp/testfile"
    prompt: '{{ __loginuser__ }}@{{ __inventory_hostname__ }}'
    timeout: 30
  
# お約束
  - expect: '@'
    exec: exit

