

- name: display data1
  shell: echo {{ VAR_01 }}

- name: display data2
  shell: echo {{ VAR_out_of_scope }}

- name: display data3
  shell: echo {{ item.one }} && echo {{ item.one }}
  loop: "{{ VAR_02 }}"

- name: display CPF_delivery_test
  shell: cat {{ CPF_delivery_test | default ('/etc/hosts',true) }}
  delegate_to: localhost
